spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://${PROD_MYSQLHOST}:${PROD_MYSQLPORT}/${PROD_MYSQLDATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${PROD_MYSQLUSER}
    password: ${PROD_MYSQLPASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


